import { NextRequest, NextResponse } from 'next/server';
import { FirefliesInsights } from '@/lib/types';

const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;

export async function POST(request: NextRequest) {
  try {
    const { transcriptSummary, meetingTitle, companyName, sourceType, selectedAgents } = await request.json();

    if (!transcriptSummary || transcriptSummary.trim().length === 0) {
      return NextResponse.json(
        { error: 'Transcript summary is required' },
        { status: 400 }
      );
    }

    if (!ANTHROPIC_API_KEY) {
      console.warn('ANTHROPIC_API_KEY not configured, using fallback');
      return NextResponse.json({
        insights: extractInsightsFallback(transcriptSummary)
      });
    }

    const sourceDescription = sourceType === 'justcall'
      ? 'Below is a phone call transcript from JustCall. Analyze it thoroughly and extract the strongest, most relevant points.'
      : sourceType === 'mixed'
      ? 'Below are transcripts from multiple sources (meetings and phone calls). Analyze ALL of them together and synthesize the strongest, most relevant points from across every interaction.'
      : 'Below are meeting notes from Fireflies.ai. There may be multiple meetings — analyze ALL of them together and synthesize the strongest, most relevant points from across every call.';

    // Map selected agents to human-readable service names
    const agentServiceMap: Record<string, string> = {
      seo: 'SEO/GEO (search engine optimization, content creation, organic traffic growth)',
      paid_ads: 'Paid Advertising (Google Ads, Meta/Facebook/Instagram Ads, AI-optimized campaigns)',
      website: 'Website Development (conversion-optimized web design)',
    };
    const selectedServices = (selectedAgents as string[] || ['seo', 'paid_ads', 'website'])
      .map(a => agentServiceMap[a] || a)
      .join(', ');
    const excludedServices = Object.entries(agentServiceMap)
      .filter(([key]) => !(selectedAgents as string[] || []).includes(key))
      .map(([, name]) => name);
    const excludeNote = excludedServices.length > 0
      ? `\n\nCRITICAL: This proposal ONLY includes these services: ${selectedServices}. Do NOT mention or reference ${excludedServices.join(' or ')} in any way. No mentions of ad accounts, ad spend, paid campaigns, bidding, ROAS, cost per click, ad creative, or any paid advertising concepts unless Paid Advertising is one of the selected services. No mentions of SEO, organic traffic, keywords, or content creation unless SEO/GEO is one of the selected services. Stay strictly within the selected services.`
      : '';

    const analysisPrompt = `You are a senior marketing strategist analyzing sales call transcripts to build a hyper-personalized proposal section. The prospect is "${companyName || 'the prospect'}".

Selected services: ${selectedServices}${excludeNote}

${sourceDescription}

--- START TRANSCRIPT DATA ---
${transcriptSummary}
--- END TRANSCRIPT DATA ---

Your job: Extract the MOST SPECIFIC, CONCRETE insights from these transcripts. Generic marketing speak = failure. Every point must reference something the prospect actually said, their specific situation, or their industry reality.

Return a JSON object with these fields:

1. "painPoints" (array of 3-5 strings) — The prospect's SPECIFIC frustrations and challenges. Rules:
   - Use their actual words/situations when possible ("struggling to get leads from their website" not "digital presence challenges")
   - Include specific numbers they mentioned (revenue, lead volume, team size, budget, etc.)
   - Reference their specific industry, market, or competitive situation
   - Only include challenges solvable by: ${selectedServices}
   - BAD: "Difficulty generating qualified leads online" 
   - GOOD: "Currently getting ~20 leads/month from their website but only 3-4 are qualified — spending time on tire-kickers who aren't ready to buy"

2. "megaSolutions" (array of 3-5 strings) — How we specifically solve each pain point. Rules:
   - Each solution MUST directly map to a pain point above
   - Reference their specific situation, not generic capabilities
   - Mention concrete deliverables and expected outcomes
   - BAD: "AI-powered optimization to improve lead quality"
   - GOOD: "Our AI agents will restructure your campaigns around qualified-lead signals — optimizing for the homeowners actually ready to hire a contractor, not just anyone clicking an ad. Expect CPQL to drop 30-40% within 60 days as the AI learns your ideal customer profile."

3. "summary" (string, 2-3 sentences) — A personalized executive summary that:
   - Addresses the prospect as "you" / "your"
   - References their specific business situation from the call
   - Connects their goals to what we'll deliver
   - Uses "we" / "our" (don't say "MEGA")
   - Feels like it was written by someone who was on the call, not generated by AI
   - BAD: "Based on our discussion, we understand your company faces marketing challenges that our AI-powered solutions can address."
   - GOOD: "Your team has built a strong reputation in the Austin market, but you're leaving growth on the table — relying on referrals while competitors are capturing the homeowners actively searching online. We'll change that by deploying always-on AI agents that put you in front of the right buyers at the right time, turning your online presence into a consistent lead engine."

4. "discussionTopics" (array of 4-8 strings) — Key business details discussed (for internal reference, not shown to prospect). Include: budget mentioned, current marketing spend, team size, decision timeline, competitors mentioned, current tools/platforms, growth goals, etc.

CRITICAL RULES:
- If the transcript is thin/vague, extrapolate intelligently from the industry and company type — but flag which points are inferred vs. stated
- Never use these phrases: "leverage", "cutting-edge", "state-of-the-art", "comprehensive solution", "holistic approach", "digital landscape", "drive results"
- Every pain point and solution should feel like it was written by someone who deeply understands THIS prospect's business
- The prospect should read this and think "they actually listened to what I said"
- **NEVER mention specific dollar amounts for MEGA's management fees, pricing, or service costs** (e.g. "$1,000/month", "$2,000/month", "$1,399/month"). The pricing section is generated separately and must be the single source of truth for all pricing. If the prospect discussed pricing on the call, reference it generically (e.g. "competitive management fee", "discounted rate to get started") — never with a specific number. You CAN mention the prospect's own numbers (ad budget, revenue, CAC targets, etc.) — just not MEGA's fees.
- **NEVER fabricate or exaggerate the prospect's current situation.** If the transcript doesn't explicitly state something (e.g. "zero organic traffic", "no online presence", "no leads"), DO NOT claim it. If you're unsure about a metric, use hedging language ("limited", "underutilized", "room to grow") — never absolute claims like "zero", "none", or "no customers from [channel]". Getting the prospect's current state wrong destroys credibility instantly. When in doubt, frame the opportunity positively ("grow from X to Y") rather than negatively ("you currently have nothing").

Respond with ONLY the JSON object.`;

    const response = await fetch('https://api.anthropic.com/v1/messages', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01'
      },
      body: JSON.stringify({
        model: 'claude-sonnet-4-20250514',
        max_tokens: 1500,
        messages: [{
          role: 'user',
          content: analysisPrompt
        }]
      })
    });

    if (!response.ok) {
      const errText = await response.text();
      console.error('Anthropic API error:', response.status, errText);
      return NextResponse.json({
        insights: extractInsightsFallback(transcriptSummary)
      });
    }

    const data = await response.json();
    const analysisText = data.content?.[0]?.text;

    if (!analysisText) {
      return NextResponse.json({
        insights: extractInsightsFallback(transcriptSummary)
      });
    }

    // Parse JSON from Claude's response
    const jsonMatch = analysisText.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      return NextResponse.json({
        insights: extractInsightsFallback(transcriptSummary)
      });
    }

    const insights: FirefliesInsights = JSON.parse(jsonMatch[0]);

    // POST-GENERATION VALIDATION: Strip any references to unselected services
    // This is a hard safety net — even if the AI ignores instructions, we catch it here
    const agents = (selectedAgents as string[]) || [];
    const hasPaidAds = agents.includes('paid_ads');
    const hasSeo = agents.includes('seo');

    const paidAdsTerms = /\b(paid ad|google ads?|meta ads?|facebook ads?|instagram ads?|ad account|ad spend|ad budget|advertising budget|cost per click|CPC|ROAS|bidding|ad creative|ad campaign|paid campaign|paid advertising|campaign optimization|campaign coordination|ad targeting)\b/gi;
    const seoTerms = /\b(SEO|organic traffic|keyword ranking|backlink|search engine optimization|content strategy|blog post|topical authority)\b/gi;

    function scrubText(text: string): string {
      if (!hasPaidAds) text = text.replace(paidAdsTerms, (match) => {
        console.warn(`[SCRUB] Removed paid ads term "${match}" from insights`);
        return 'marketing';
      });
      // Don't scrub SEO terms since they're less likely to be wrong,
      // but flag them if SEO isn't selected
      return text;
    }

    function scrubArray(arr: string[]): string[] {
      if (!hasPaidAds) {
        // Remove entire items that are fundamentally about paid ads
        arr = arr.filter(item => {
          const lower = item.toLowerCase();
          const isPaidAds = lower.includes('google ads') || lower.includes('ad account') || 
                           lower.includes('ad spend') || lower.includes('paid advertising') ||
                           lower.includes('cost per click') || lower.includes('ad campaign');
          if (isPaidAds) console.warn(`[SCRUB] Removed paid-ads item: "${item.substring(0, 80)}..."`);
          return !isPaidAds;
        });
      }
      return arr.map(scrubText);
    }

    insights.painPoints = scrubArray(insights.painPoints);
    insights.megaSolutions = scrubArray(insights.megaSolutions);
    insights.discussionTopics = scrubArray(insights.discussionTopics);
    insights.summary = scrubText(insights.summary);

    return NextResponse.json({ insights });

  } catch (error) {
    console.error('Transcript analysis error:', error);
    return NextResponse.json(
      { error: 'Failed to analyze transcript' },
      { status: 500 }
    );
  }
}

/** Fallback: extract basic insights from the summary text without AI */
function extractInsightsFallback(summary: string): FirefliesInsights {
  const lines = summary.split('\n').filter(l => l.trim());
  const bulletPoints = lines.filter(l => l.match(/^[-•*]/));
  
  return {
    painPoints: bulletPoints.slice(0, 3).map(l => l.replace(/^[-•*]\s*\*?\*?/, '').replace(/\*\*/g, '').trim()).filter(Boolean),
    discussionTopics: bulletPoints.slice(3, 7).map(l => l.replace(/^[-•*]\s*\*?\*?/, '').replace(/\*\*/g, '').trim()).filter(Boolean),
    megaSolutions: [
      'AI-powered marketing optimization tailored to your specific needs',
      'End-to-end management with dedicated account support',
      'Data-driven lead scoring and qualification framework'
    ],
    summary: 'Based on our conversation, we\'ve prepared this proposal to address your specific marketing challenges with a data-driven, AI-powered approach that delivers measurable results.'
  };
}
